### ISSUE TITLE
Add retries to Go binary download

### ISSUE THREAD

**Issue by edmorley** [heroku/buildpacks-go#361]
To reduce the chance of intermittent failures like this (seen on Direwolf; production US cloud job ID `8c72f519-f19d-45d6-a735-299a68d2cd3b`, `2025-03-30T16:41:51.862Z`):

```
remote: Building source:        
remote: Heroku Labs: Build Time Config Vars are *not enabled*.        
remote: By default, your config vars are only available at runtime. See https://devcenter.heroku.com/build-time-config-vars for details on Build Time Config Vars.        
remote: Waiting on build...        
remote: Extracting source        
remote: Downloading buildpack urn:cnb:registry:heroku/go        
remote: Downloading buildpack urn:cnb:registry:heroku/procfile        
remote: Image with name "direwolf-819c491072/builds" not found        
remote: heroku/go       0.5.7        
remote: heroku/procfile 4.2.0        
remote: [0m[1m[35m[0m        
remote: [0m[1m[35m[Reading build configuration][0m        
remote: Detected Go version requirement: =1.23        
remote: Resolved Go version: go1.23.7 (linux-arm64)        
remote: [0m[1m[35m[0m        
remote: [0m[1m[35m[Installing Go distribution][0m        
remote: Installing go1.23.7 (linux-arm64) from https://go.dev/dl/go1.23.7.linux-arm64.tar.gz        
remote: [0m[1m[31m[0m        
remote: [0m[1m[31m[Error: Heroku Go Buildpack distribution layer error][0m        
remote: [0m[31mCouldn't extract Go distribution archive: HTTP error while fetching archive: https://go.dev/dl/go1.23.7.linux-arm64.tar.gz: status code 500[0m        
remote: [31;1mERROR: [0mfailed to build: exit status 1        
remote: Verifying deploy...        
remote: 
remote: !	Push rejected to direwolf-819c491072.   
```

cc @joshwlewis

**Comment by edmorley** [comment]
(The Direwolf job actually saw HTTP 500s from `go.dev` twice in a row, so failed even though Direwolf retries once)

**Comment by edmorley** [comment]
Another Direwolf failure in job `b1f75d48-011a-4007-a769-d8540d601c19`, `2025-06-05T16:37:50.669Z`:

```
    remote: [1;35m## Heroku Go Buildpack[0m        
    remote: 
    remote: - Reading build configuration        
    remote:   - Detected Go version requirement: =1.23        
    remote:   - Resolved Go version: go1.23.9 (linux-arm64)        
    remote: - Installing Go distribution        
    remote:   - Installing go1.23.9 (linux-arm64) from https://go.dev/dl/go1.23.9.linux-arm64.tar.gz        
    remote: 
    remote: [0;31m! Heroku Go Buildpack distribution layer error[0m        
    remote: [0;31m![0m        
    remote: [0;31m! Couldn't extract Go distribution archive: HTTP error while fetching archive: https://go.dev/dl/go1.23.9.linux-arm64.tar.gz: status code 500[0m        
    remote: 
    remote: [31;1mERROR: [0mfailed to build: exit status 1        
    remote: [34m🏁 [16:42:53.106] +15.106s     Ended builder phase (501ms)[0m
```
